server:
  port: 9296

spring:
  application:
    name: CLOUD-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/M-ds/spring-cloud-example
          clone-on-start: true
